#----------------------DATABASE----------------------#
databaseLink: "dataBase/database.db"
#----------------------SPAWN----------------------#
spawnWorldName: "world"
spawnX: 1
spawnY: 10
spawnZ: 5
#----------------------ACTIONS----------------------#
#----------PAPER_ITEM_FRAME----------
PAPER_ITEM_FRAME_TITLE: ""
PAPER_ITEM_FRAME_SUBTITLE: ""
#NOMBRE DEL MUNDO:
PAPER_ITEM_FRAME_WORLD: ""
#LOCATION DEL ITEM_FRAME:
PAPER_ITEM_FRAME_X: 1
PAPER_ITEM_FRAME_Y: 2
PAPER_ITEM_FRAME_Z: 3
#----------PAPER_ITEM_FRAME2----------
PAPER_ITEM_FRAME2_TITLE: ""
PAPER_ITEM_FRAME2_SUBTITLE: ""
#NOMBRE DEL MUNDO:
PAPER_ITEM_FRAME2_WORLD: ""
#LOCATION DEL ITEM_FRAME:
PAPER_ITEM_FRAME2_X: 1
PAPER_ITEM_FRAME2_Y: 2
PAPER_ITEM_FRAME2_Z: 3
#----------PAPER_ITEM_FRAME_SELECTION----------
PAPER_ITEM_FRAME_SELECTION_TITLE: ""
PAPER_ITEM_FRAME_SELECTION_SUBTITLE: ""
#NOMBRE DEL MUNDO:
PAPER_ITEM_FRAME_SELECTION_COMMON_LOC_WORLD_NAME: ""
#ITEM FRAME CORRECTO:
PAPER_ITEM_FRAME_SELECTION_CORRECT_LOC_X: 1
PAPER_ITEM_FRAME_SELECTION_CORRECT_LOC_Y: 2
PAPER_ITEM_FRAME_SELECTION_CORRECT_LOC_Z: 3
#PRIMER ITEM FRAME FALSO:
PAPER_ITEM_FRAME_SELECTION_TRICK_LOC_X: 1
PAPER_ITEM_FRAME_SELECTION_TRICK_LOC_Y: 2
PAPER_ITEM_FRAME_SELECTION_TRICK_LOC_Z: 3
#SEGUNDO ITEM FRAME FALSO:
PAPER_ITEM_FRAME_SELECTION_TRICK2_LOC_X: 1
PAPER_ITEM_FRAME_SELECTION_TRICK2_LOC_Y: 2
PAPER_ITEM_FRAME_SELECTION_TRICK2_LOC_Z: 3
#----------BUTTON_MOVEMENT----------
BUTTON_MOVEMENT_TITLE: ""
BUTTON_MOVEMENT_SUBTITLE: ""
#NOMBRE DEL MUNDO:
BUTTON_MOVEMENT_COMMON_LOC_WORLD_NAME: ""
#PRIMERA LOCATION DE BOTON
BUTTON_MOVEMENT_0_X: 1
BUTTON_MOVEMENT_0_Y: 2
BUTTON_MOVEMENT_0_Z: 3
#SEGUNDA LOCATION DE BOTON
BUTTON_MOVEMENT_1_X: 1
BUTTON_MOVEMENT_1_Y: 2
BUTTON_MOVEMENT_1_Z: 3
#TERCERA LOCATION DE BOTON
BUTTON_MOVEMENT_2_X: 1
BUTTON_MOVEMENT_2_Y: 2
BUTTON_MOVEMENT_2_Z: 3
#CUARTA LOCATION DE BOTON
BUTTON_MOVEMENT_3_X: 1
BUTTON_MOVEMENT_3_Y: 2
BUTTON_MOVEMENT_3_Z: 3
#QUINTA LOCATION DE BOTON
BUTTON_MOVEMENT_4_X: 1
BUTTON_MOVEMENT_4_Y: 2
BUTTON_MOVEMENT_4_Z: 3
#SEXTA LOCATION DE BOTON
BUTTON_MOVEMENT_5_X: 1
BUTTON_MOVEMENT_5_Y: 2
BUTTON_MOVEMENT_5_Z: 3
#SEPTIMA LOCATION DE BOTON
BUTTON_MOVEMENT_6_X: 1
BUTTON_MOVEMENT_6_Y: 2
BUTTON_MOVEMENT_6_Z: 3
#OCTAVA LOCATION DE BOTON
BUTTON_MOVEMENT_7_X: 1
BUTTON_MOVEMENT_7_Y: 2
BUTTON_MOVEMENT_7_Z: 3
buttonBlockFace: ""
#----------ITEM_CATCH----------
ITEM_CATCH_TITLE: ""
ITEM_CATCH_SUBTITLE: ""
#NOMBRE DEL MUNDO:
ITEM_CATCH_COMMON_LOC_WORLD_NAME: ""
#PRIMERA LOCATION DE SPAWN ITEMS:
ITEM_CATCH_1_X: 1
ITEM_CATCH_1_Y: 2
ITEM_CATCH_1_Z: 3
#SEGUNDA LOCATION DE SPAWN ITEMS:
ITEM_CATCH_2_X: 1
ITEM_CATCH_2_Y: 2
ITEM_CATCH_2_Z: 3
#TERCERA LOCATION DE SPAWN ITEMS:
ITEM_CATCH_3_X: 1
ITEM_CATCH_3_Y: 2
ITEM_CATCH_3_Z: 3
#CUARTA LOCATION DE SPAWN ITEMS:
ITEM_CATCH_4_X: 1
ITEM_CATCH_4_Y: 2
ITEM_CATCH_4_Z: 3
#QUINTA LOCATION DE SPAWN DE ITEMS:
ITEM_CATCH_5_X: 1
ITEM_CATCH_5_Y: 2
ITEM_CATCH_5_Z: 3
#SEXTA LOCATION DE SPAWN DE ITEMS:
ITEM_CATCH_6_X: 1
ITEM_CATCH_6_Y: 2
ITEM_CATCH_6_Z: 3
#SEPTIMA LOCATION DE SPAWN DE ITEMS:
ITEM_CATCH_7_X: 1
ITEM_CATCH_7_Y: 2
ITEM_CATCH_7_Z: 3
#OCTAVA LOCATION DE SPAWN DE ITEMS:
ITEM_CATCH_8_X: 1
ITEM_CATCH_8_Y: 2
ITEM_CATCH_8_Z: 3
#NOVENA LOCATION DE SPAWN DE ITEMS:
ITEM_CATCH_9_X: 1
ITEM_CATCH_9_Y: 2
ITEM_CATCH_9_Z: 3
#----------PRESSURE_PLATE----------
PRESSURE_PLATE_TITLE: ""
PRESSURE_PLATE_SUBTITLE: ""
#NOMBRE DEL MUNDO:
PRESSURE_PLATE_COMMON_LOC_WORLD_NAME: ""
#LOCATION DE PLACA ABEDUL:
PRESSURE_PLATE_BIRCH_X: 1
PRESSURE_PLATE_BIRCH_Y: 2
PRESSURE_PLATE_BIRCH_Z: 3
#LOCATION DE PLACA ROBLE:
PRESSURE_PLATE_OAK_X: 1
PRESSURE_PLATE_OAK_Y: 2
PRESSURE_PLATE_OAK_Z: 3
#LOCATION DE PLACA JUNGLA:
PRESSURE_PLATE_JUNGLE_X: 1
PRESSURE_PLATE_JUNGLE_Y: 2
PRESSURE_PLATE_JUNGLE_Z: 3
#----------PAPER_ITEM_FRAME_SELECTION2----------
THREE_ITEM_FRAMES_TITLE: ""
THREE_ITEM_FRAMES_SUBTITLE: ""
#NOMBRE DEL MUNDO:
THREE_ITEM_FRAMES_COMMON_LOC_WORLD_NAME: ""
#PRIMER ITEM FRAME:
THREE_ITEM_FRAMES_FIRST_LOC_X: 1
THREE_ITEM_FRAMES_FIRST_LOC_Y: 2
THREE_ITEM_FRAMES_FIRST_LOC_Z: 3
#SEGUNDO ITEM FRAME:
THREE_ITEM_FRAMES_SECOND_LOC_X: 1
THREE_ITEM_FRAMES_SECOND_LOC_Y: 2
THREE_ITEM_FRAMES_SECOND_LOC_Z: 3
#TERCER ITEM FRAME:
THREE_ITEM_FRAMES_THIRD_LOC_X: 1
THREE_ITEM_FRAMES_THIRD_LOC_Y: 2
THREE_ITEM_FRAMES_THIRD_LOC_Z: 3
#----------PRESS_BUTTON----------
PRESS_BUTTON_TITLE: ""
PRESS_BUTTON_SUBTITLE: ""
#NOMBRE DEL MUNDO:
PRESS_BUTTON_COMMON_LOC_WORLD_NAME: ""
#LOCATION DEL BOTON
PRESS_BUTTON_BUTTON_X: 1
PRESS_BUTTON_BUTTON_Y: 2
PRESS_BUTTON_BUTTON_Z: 3
#LOCATION DEL FRAME
PRESS_BUTTON_FRAME_X: 1
PRESS_BUTTON_FRAME_Y: 2
PRESS_BUTTON_FRAME_Z: 3
#LOCATION DEL ITEM_FRAME
PRESS_BUTTON_ITEM_FRAME_X: 1
PRESS_BUTTON_ITEM_FRAME_Y: 2
PRESS_BUTTON_ITEM_FRAME_Z: 3
#----------FLOOR_IS_LAVA----------
FLOOR_IS_LAVA_TITLE: ""
FLOOR_IS_LAVA_SUBTITLE: ""
#NOMBRE DEL MUNDO:
FLOOR_IS_LAVA_COMMON_LOC_WORLD_NAME: ""
#LOCATION DE LA PRIMERA ESQUINA
FLOOR_IS_LAVA_FIRST_CORNER_X: 1
FLOOR_IS_LAVA_FIRST_CORNER_Y: 2
FLOOR_IS_LAVA_FIRST_CORNER_Z: 3
#LOCATION DE LA SEGUNDA ESQUINA
FLOOR_IS_LAVA_SECOND_CORNER_X: 1
FLOOR_IS_LAVA_SECOND_CORNER_Y: 2
FLOOR_IS_LAVA_SECOND_CORNER_Z: 3
#MENSAJES
correctBlockAnnounceMessage: ""
correctPressurePlateMessage: ""
